CompanyDirectoryDF/Controllers/EmergencyListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CompanyDirectoryDF.Models;
using CompanyDirectoryDF.ViewModel;
using System.Web.UI;

namespace CompanyDirectoryDF.Controllers
{
    public class EmergencyListController : Controller
    {
       
        private CompanyDirectoryDFEntities db = new CompanyDirectoryDFEntities();
        // GET: EmergencyList
      
        // GET: PhoneLists
        public ActionResult Index()
        {
            var phoneLists = db.PhoneLists
                .Include(p => p.Directory)
                .Include(p => p.Employee)
                .Include(p => p.PhoneListName);

            var phoneList = phoneLists.ToList();

            List<EmergencyList> listOfEmoLists = new List<EmergencyList>();

            var prevList = "";
            EmergencyList el = new EmergencyList();
            

            foreach (PhoneList pl in phoneList)
            {
                if (listOfEmoLists.Count == 0) 
                {
                    AddNewEmergencyList(ref listOfEmoLists, pl);
                }
                else
                {
                    bool addNewList = true;
                    foreach (EmergencyList EmoListItem in listOfEmoLists)
                    {
                        if(pl.PhoneListNameID == EmoListItem.EmergencyListID)
                        {
                          EmoListItem.EmployeesInEmergencyList.Add(pl.Employee);
                          addNewList = false;
                          break;
                        }
                    }
                    if(addNewList)
                        AddNewEmergencyList(ref listOfEmoLists, pl);

                }
           }
            return View(listOfEmoLists);
        }

        private static void AddNewEmergencyList(ref List<EmergencyList> listOfEmergencyContacts, PhoneList pl){
            EmergencyList el = new EmergencyList();

            el.EmergencyListID = pl.PhoneListNameID;
            el.EmergencyListName = pl.PhoneListName.Name;
            el.EmployeesInEmergencyList.Add(pl.Employee);

            listOfEmergencyContacts.Add(el);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var phoneLists = db.PhoneLists
                  .Include(p => p.Directory)
                  .Include(p => p.Employee)
                  .Include(p => p.PhoneListName)
                  .Where(p => p.PhoneListName.ID == id);

            var phoneList = phoneLists.ToList();
            List<EmergencyList> listOfEmoLists = new List<EmergencyList>();

            var prevList = "";
            EmergencyList el = new EmergencyList();
            List<Employee> empList = new List<Employee>();
            foreach (PhoneList pl in phoneList)
            {
                if (prevList != pl.PhoneListNameID.ToString())
                {
                    if (prevList != "")
                        listOfEmoLists.Add(el);

                    el = new EmergencyList();


                    ViewBag.AddToPhoneListId = pl.ID;
                    el.PhonelistID = pl.ID;
                    el.EmergencyListID = id;
                    el.EmergencyListName = pl.PhoneListName.Name;
                    el.EmployeesInEmergencyList.Add(pl.Employee);
                    
                    prevList = pl.PhoneListNameID.ToString();
                }
                else
                {
                    el.EmployeesInEmergencyList.Add(pl.Employee);
                }
            }
            listOfEmoLists.Add(el);



            return View(listOfEmoLists);
        }
        
        [HttpPost] //This should be a post with a Security Token. 
        public ActionResult Delete(string hdnValue, string phonelistId, string EmergencyListID )
        {
            //PhoneList phoneList = db.PhoneLists.Where(c => c.EmployeeID == Convert.ToInt32(hdnValue));
            PhoneList phoneList = db.PhoneLists.Find(Convert.ToInt32(hdnValue));
            int empId = Convert.ToInt32(hdnValue);
            int emgListType = Convert.ToInt32(EmergencyListID);
            List<PhoneList> dddd = db.PhoneLists.Where(x => x.EmployeeID == empId).Where(x => x.PhoneListNameID == emgListType).ToList();// This is not the best way to do this. Should refactor the ViewModel. 
        
            db.PhoneLists.Remove(dddd[0]);
            db.SaveChanges();
            return RedirectToAction("Edit", new { id = Convert.ToInt32(EmergencyListID) });
        }

        public ActionResult Add(int? listId)
        {
            PhoneList phlist = new PhoneList();
            phlist.PhoneListNameID = listId;
            phlist.DirectoryID = 1;

            //ViewBag.DirectoryID = new SelectList(db.Directories, "ID", "Name");
            ViewBag.EmployeeID = new SelectList(db.Employees, "ID", "FullName");
            //ViewBag.PhoneListNameID = new SelectList(db.PhoneListNames, "ID", "Name");

            return View(phlist);
        }

        public ActionResult Create() 
        {
            PhoneListObj plo = new PhoneListObj();
            plo.EmployeesWithInclude_List = new List<EmployesWithInclude>();

            var empsList  = db.Employees.ToList();        
            foreach (var emp in empsList)
            {
                plo.EmployeesWithInclude_List.Add(new EmployesWithInclude()
                    {
                        FirstName = emp.FirstName,
                        ID = emp.ID,
                        Include = false
                    }
                    );
                           
            }
           plo.PhoneListTypes = new SelectList(db.PhoneListTypes.ToList(), "Id", "Type");
           return View(plo);
        }

        [HttpPost]
        public ActionResult Create(PhoneListObj plo){

            PhoneListName pln = new PhoneListName();

          
            pln.TypeID = 2;
            pln.Name = "DeleteMe";
            db.PhoneListNames.Add(pln);
            db.SaveChanges();


            ViewBag["Status"] = "PassFail";
            return View(plo);
        }




        // POST: PhoneLists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(PhoneList phoneList)
        {
            if (ModelState.IsValid)
            {
               
                db.PhoneLists.Add(phoneList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DirectoryID = new SelectList(db.Directories, "ID", "Name", phoneList.DirectoryID);
            ViewBag.EmployeeID = new SelectList(db.Employees, "ID", "FirstName", phoneList.EmployeeID);
            ViewBag.PhoneListNameID = new SelectList(db.PhoneListNames, "ID", "Name", phoneList.PhoneListNameID);
            return View(phoneList);
        }
      
    }
}

//http://dotnetslackers.com/articles/aspnet/Understanding-ASP-NET-MVC-Model-Binding.aspx

CompanyDirectoryDF/Views/EmergencyList/Add.cshtml
@model CompanyDirectoryDF.Models.PhoneList

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
    }

<h2>Add</h2>

@using (Html.BeginForm()) 
{
    

    
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Emergency Contact</h4>
        <hr />
    

        @*@Html.Hidden("PhoneListNameID", Model.PhoneListNameID)
        @Html.Hidden("DirectoryID", Model.DirectoryID)*@


        @Html.HiddenFor(model => model.PhoneListNameID)
        @Html.HiddenFor(model => model.DirectoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, "EmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Employee To List" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CompanyDirectoryDF/Views/EmergencyList/Create.cshtml
@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm())
{
    <input id="Submit1" type="submit" value="submit" />
}

<h2>Create</h2>

CompanyDirectoryDF/Views/EmergencyList/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

CompanyDirectoryDF/Views/EmergencyList/Edit.cshtml
@model IEnumerable<CompanyDirectoryDF.ViewModel.EmergencyList>

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    function boo(id) {
        $('#hdnValue').val(id);
        $('#PhonelistID').val();
      
    };
    function boom(id)
    {
        $('#EmergencyListID').val(id);
       
    }
</script>


<h2>Edit Emergency List</h2>
<p>
    @foreach (var item in Model)
    {
        @Html.ActionLink("Add", "Add", new {listId = item.EmergencyListID})
    } | 
    @Html.ActionLink("Back to List", "Index")
</p>


@using (Html.BeginForm("Delete", "EmergencyList"))
{
    @Html.Hidden("hdnValue", "")
    <table class="table">
        @foreach (var item in Model)
        {
           
            <tr>
                <td>
                    <b> 
                    @Html.DisplayFor(modelItem => item.EmergencyListName)</b>
                   
                    @Html.Hidden("EmergencyListID", item.EmergencyListID)
                </td>
            </tr>

            foreach (var emp in item.EmployeesInEmergencyList)
            {
                <tr>
                    <td>
                        <span style="padding:0 6px;">@Html.DisplayFor(ModelItem => emp.FullName)  </span>
                    </td>
                    <td>
                        <div class="form-actions no-color">
                            @Html.Hidden("PhonelistId", item.PhonelistID)
                            <input id="@emp.ID" type="submit" value="DELETE" name="submit" onclick="boo(this.id); boom(@item.EmergencyListID);" />

                        </div>
                    </td>
                </tr>
            }




        }



    </table>
}

CompanyDirectoryDF/Views/EmergencyList/Index.cshtml
@model IEnumerable<CompanyDirectoryDF.ViewModel.EmergencyList>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .EmergencyContact {position:relative; padding:0 6px; cursor:pointer;}
    .EmergencyContact div{display:none;}
    .EmergencyContact:hover div{display:block;}
    .EmergencyContactNumber{ position:absolute;  background-color:black; color:white; top:-15px; left:25px; -moz-border-radius:3px; -webkit-border-radius:3px; border-radius:3px; z-index:50; }
    .EmergencyContactNumber a{color:white;}
    .EmergencyContactNumber table{width:250px;}
    .EmergencyContactNumber table tr th{text-align:center;}
    .EmergencyContactNumber table tr td{padding:8px; }
     .EmergencyContactNumber table th div{padding:3px; background-color:#0c8fee; -moz-border-radius:3px; -webkit-border-radius:3px; border-radius:3px; }
</style>

<h2>Emeregency Contact List</h2>
<p>
    @Html.ActionLink("Create", "Create", "EmergencyList") |
    @Html.ActionLink("Back to Directory", "index", "EmployeeDirectory")
</p>

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <b> @Html.DisplayFor(modelItem => item.EmergencyListName)</b>
            </td>
            @foreach (var emp in item.EmployeesInEmergencyList)
            {
                <td>

                    <div class="EmergencyContact">
                        @Html.DisplayFor(ModelItem => emp.FullName)
                        <div class="EmergencyContactNumber">
                            <table >
                                <tr>
                                    <th><div> @Html.DisplayFor(ModelItem => emp.FullName) </div> </th>
                                </tr>
                                <tr>
                                    <td>@Html.LabelFor(ModelItem => emp.CellPhone)  : <a href="tel:@emp.CellPhone">@Html.DisplayFor(m => emp.CellPhoneAsLong)</a> </td>
                                </tr>
                                <tr>
                                    <td>@Html.LabelFor(ModelItem => emp.HomePhone)  : <a href="tel:@emp.HomePhone"> @Html.DisplayFor(m => emp.HomePhoneAsLong)</a> </td>
                                </tr>
                                <tr>
                                    <td>@Html.LabelFor(ModelItem => emp.OfficePhone)  : <a href="tel:@emp.OfficePhone">@Html.DisplayFor(m => emp.OfficePhoneAsLong)</a> ext: @emp.Ext </td>
                                </tr>
                            </table>
                        </div>
                    </div>

                </td>
            }
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.EmergencyListID })
            </td>
        </tr>
    }
</table>